apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_TEAM-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: DEPLOYMENT_TEAM
  template:
    metadata:
      labels:
        app: DEPLOYMENT_TEAM
    spec:
      containers:
        - name: DEPLOYMENT_TEAM
          image: dhanashree1572/flask-demo-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: DEPLOYMENT_TEAM-ssvc
spec:
  selector:
    app: DEPLOYMENT_TEAM
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
