apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-team-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-team
  template:
    metadata:
      labels:
        app: deployment-team
    spec:
      containers:
        - name: deployment-team
          image: dhanashree1572/flask-demo-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: deployment-team-ssvc
spec:
  selector:
    app: deployment-team
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
